### PR TITLE
Change to biber + minor improvements

### PR DESCRIPTION
**Pull request by dekuenstle**
See commit messages to see what changes and especially why.

! All changes should (but are not in this pr) also be made in the vorlage/ directory !

### CODE REVIEW

**Comment by Trybnetic** [comment]
Thanks for your improvements!

But is the `rm -rf auto/ */auto` in the Makefile really necessary? And if it is, for which purpose?

**Comment by dekuenstle** [comment]
You're right, i think you can drop this line.

These directories sometimes get created by something in my latex dev stack, but i'm not sure by which programm.

Btw: There is also the tool [latexmk](https://www.ctan.org/pkg/latexmk/?lang=en) which can automate the correct call order of pdflatex, biber,..., allows automated reruns on file change and adds cleanup functionality. But of course it's an additional installation for the students.

**Comment by Trybnetic** [comment]
Ah ok, for me it doesn't seem like the directory is produced by biber.

I will check latexmk, but it's probably over-fitting for the students, even though it seems quiet nice for this purpose.

**Comment by Trybnetic** [comment]
I've deleted the line in Makefiles and did the changes in vorlage/ according to your improvements in beispiel/ 

Would be great if you could counter-check this ;-)

**Comment by dekuenstle** [comment]
Looks fine!

**Pull request merged**
